[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bball"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
  "ortools",
  "rich",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "pytest",
]

[tool.uv]
required-version = ">0.9"
